spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/academic;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  #port: 8080
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      pattern: "%t %a %s \"%r\" %b (%D ms)"
      directory: log
      suffix: .log
      prefix: access


#thymeleaf:
  #prefix: classpath:/templates/
  #suffix: .html